### ISSUE TITLE
Bug: "Launching server using runtime node failed. Error: spawn node ENOENT"

### ISSUE THREAD

**Issue by thernstig** [microsoft/vscode-eslint#1596]
Type: <b>Bug</b>

At times when starting VS Code the ESLint server is stopped. It happens intermittently and quite seldom. Using the command `ESLint: Restart ESLint Server` does not help. Here is the output from the OUTPUT panel.

```sh
[Info  - 11:21:39 AM] ESLint server is starting
[Info  - 11:21:40 AM] ESLint server stopped.
[Error - 11:21:40 AM] ESLint client: couldn't create connection to server.
Launching server using runtime node failed. Error: spawn node ENOENT
[Error - 11:21:40 AM] Starting the server failed.
Launching server using runtime node failed. Error: spawn node ENOENT

### Here I executed the command 'ESLint: Restart ESLint Server' from the command palette ###

[Error - 11:23:15 AM] Restarting client failed
Error: Client is not running and can't be stopped. It's current state is: startFailed
	at w.shutdown (/home/userA/.vscode-server/extensions/dbaeumer.vscode-eslint-2.2.6/client/out/extension.js:1:107590)
	at w.stop (/home/userA/.vscode-server/extensions/dbaeumer.vscode-eslint-2.2.6/client/out/extension.js:1:107171)
	at w.stop (/home/userA/.vscode-server/extensions/dbaeumer.vscode-eslint-2.2.6/client/out/extension.js:1:266246)
	at w.restart (/home/userA/.vscode-server/extensions/dbaeumer.vscode-eslint-2.2.6/client/out/extension.js:1:266113)
	at /home/userA/.vscode-server/extensions/dbaeumer.vscode-eslint-2.2.6/client/out/extension.js:1:376159
	at s.h (/home/userA/.vscode-server/bin/97dec172d3256f8ca4bfb2143f3f76b503ca0534/out/vs/workbench/api/node/extensionHostProcess.js:94:107622)
	at s.$executeContributedCommand (/home/userA/.vscode-server/bin/97dec172d3256f8ca4bfb2143f3f76b503ca0534/out/vs/workbench/api/node/extensionHostProcess.js:94:108311)
	at u.N (/home/userA/.vscode-server/bin/97dec172d3256f8ca4bfb2143f3f76b503ca0534/out/vs/workbench/api/node/extensionHostProcess.js:104:11208)
	at u.M (/home/userA/.vscode-server/bin/97dec172d3256f8ca4bfb2143f3f76b503ca0534/out/vs/workbench/api/node/extensionHostProcess.js:104:10926)
	at u.H (/home/userA/.vscode-server/bin/97dec172d3256f8ca4bfb2143f3f76b503ca0534/out/vs/workbench/api/node/extensionHostProcess.js:104:10019)
	at u.G (/home/userA/.vscode-server/bin/97dec172d3256f8ca4bfb2143f3f76b503ca0534/out/vs/workbench/api/node/extensionHostProcess.js:104:9000)
	at /home/userA/.vscode-server/bin/97dec172d3256f8ca4bfb2143f3f76b503ca0534/out/vs/workbench/api/node/extensionHostProcess.js:104:7788
	at d.invoke (/home/userA/.vscode-server/bin/97dec172d3256f8ca4bfb2143f3f76b503ca0534/out/vs/workbench/api/node/extensionHostProcess.js:63:145)
	at v.deliver (/home/userA/.vscode-server/bin/97dec172d3256f8ca4bfb2143f3f76b503ca0534/out/vs/workbench/api/node/extensionHostProcess.js:63:2029)
	at g.fire (/home/userA/.vscode-server/bin/97dec172d3256f8ca4bfb2143f3f76b503ca0534/out/vs/workbench/api/node/extensionHostProcess.js:63:1667)
	at h.fire (/home/userA/.vscode-server/bin/97dec172d3256f8ca4bfb2143f3f76b503ca0534/out/vs/workbench/api/node/extensionHostProcess.js:72:14314)
	at /home/userA/.vscode-server/bin/97dec172d3256f8ca4bfb2143f3f76b503ca0534/out/vs/workbench/api/node/extensionHostProcess.js:120:15804
	at d.invoke (/home/userA/.vscode-server/bin/97dec172d3256f8ca4bfb2143f3f76b503ca0534/out/vs/workbench/api/node/extensionHostProcess.js:63:145)
	at v.deliver (/home/userA/.vscode-server/bin/97dec172d3256f8ca4bfb2143f3f76b503ca0534/out/vs/workbench/api/node/extensionHostProcess.js:63:2029)
	at g.fire (/home/userA/.vscode-server/bin/97dec172d3256f8ca4bfb2143f3f76b503ca0534/out/vs/workbench/api/node/extensionHostProcess.js:63:1667)
	at h.fire (/home/userA/.vscode-server/bin/97dec172d3256f8ca4bfb2143f3f76b503ca0534/out/vs/workbench/api/node/extensionHostProcess.js:72:14314)
	at c.y (/home/userA/.vscode-server/bin/97dec172d3256f8ca4bfb2143f3f76b503ca0534/out/vs/workbench/api/node/extensionHostProcess.js:72:17324)
	at /home/userA/.vscode-server/bin/97dec172d3256f8ca4bfb2143f3f76b503ca0534/out/vs/workbench/api/node/extensionHostProcess.js:72:15795
	at d.invoke (/home/userA/.vscode-server/bin/97dec172d3256f8ca4bfb2143f3f76b503ca0534/out/vs/workbench/api/node/extensionHostProcess.js:63:145)
	at v.deliver (/home/userA/.vscode-server/bin/97dec172d3256f8ca4bfb2143f3f76b503ca0534/out/vs/workbench/api/node/extensionHostProcess.js:63:2029)
	at g.fire (/home/userA/.vscode-server/bin/97dec172d3256f8ca4bfb2143f3f76b503ca0534/out/vs/workbench/api/node/extensionHostProcess.js:63:1667)
	at g.acceptChunk (/home/userA/.vscode-server/bin/97dec172d3256f8ca4bfb2143f3f76b503ca0534/out/vs/workbench/api/node/extensionHostProcess.js:72:12045)
	at /home/userA/.vscode-server/bin/97dec172d3256f8ca4bfb2143f3f76b503ca0534/out/vs/workbench/api/node/extensionHostProcess.js:72:11332
	at d.invoke (/home/userA/.vscode-server/bin/97dec172d3256f8ca4bfb2143f3f76b503ca0534/out/vs/workbench/api/node/extensionHostProcess.js:63:145)
	at v.deliver (/home/userA/.vscode-server/bin/97dec172d3256f8ca4bfb2143f3f76b503ca0534/out/vs/workbench/api/node/extensionHostProcess.js:63:2029)
	at g.fire (/home/userA/.vscode-server/bin/97dec172d3256f8ca4bfb2143f3f76b503ca0534/out/vs/workbench/api/node/extensionHostProcess.js:63:1667)
	at g.t (/home/userA/.vscode-server/bin/97dec172d3256f8ca4bfb2143f3f76b503ca0534/out/vs/workbench/api/node/extensionHostProcess.js:72:25895)
```

Using the terminal, `node` does exist:
```sh
> node --version
v18.12.1
> which node
/home/userA/.local/share/nvm/v18.12.1/bin/node
```

I have set `"eslint.runtime": "node",` both in the user and workspace settings.json files.

I have no idea what could be wrong. I have been using the ESLint extension for years, but this started to happen more recently within the past few months.

Extension version: 2.2.6
VS Code version: Code 1.74.3 (97dec172d3256f8ca4bfb2143f3f76b503ca0534, 2023-01-09T16:59:02.252Z)
OS version: Windows_NT x64 10.0.19044
Modes:
Sandboxed: No
Remote OS version: Linux x64 5.4.0-137-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz (8 x 2611)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.69GB (18.23GB free)|
|Process Argv|--crash-reporter-id e332dab4-91ea-49d1-8a1f-d8f6e06fa4e1|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: vm|
|OS|Linux x64 5.4.0-137-generic|
|CPUs|Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz (8 x 2394)|
|Memory (System)|31.33GB (27.66GB free)|
|VM|18%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vscaat:30438848
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
azure-dev_surveyonecf:30548226
pyindex848cf:30577861
nodejswelcome1cf:30587006
2e4cg342:30602488
f6dab269:30613381

```

</details>

**Comment by dbaeumer** [comment]
Very hard to say why the node runtime is not found. 

Why are you using your own? VS Code ships with a node runtime that is suitable for most use cases. Can you try to remove the settings `eslint.runtime` and see what happens?

**Comment by rdsedmundo** [comment]
This started to happen to me randomly too, had never seen it before using the extension for years. Removing `eslint.runtime` makes it work again with the default Node version, but I wanted it to use my specific version.

**Comment by thernstig** [comment]
@dbaeumer the use case to use our own runtime is of course that all our ESLint tests run with constructs available in the Node.js version we use? Or am I missing something?

**Comment by dbaeumer** [comment]
In which setting file do you make that change. If you are running for example in WSL you need to change that setting in the Remote settings  <img width="218" alt="image" src="https://user-images.githubusercontent.com/1931590/224637556-b9540ace-7d65-4271-88aa-a9e33d8e6111.png"> and not in the User settings.

**Comment by thernstig** [comment]
We run with remote SSH, and set the setting in the workspace settings. Would it work if we set them in the remote SSH settings?

![image](https://user-images.githubusercontent.com/30827238/224648154-5c456595-c7b8-4d31-99cf-4eb99bce8afa.png)

We have had them set in the workspace settings for a long time, does that mean it never worked? Why is the setting not greyed out like it is in the user settings then (I can see reasons for this, but asking as a sanity question)?

![image](https://user-images.githubusercontent.com/30827238/224648370-c4c5d958-03f7-4503-a1f5-929ae08c852c.png)

But our end goal is this: We are a team of developers that always install Node on our local machines, all using the same version (we enforce it via nvm). We want to make sure all of us use the same version of the node binary, due to that ESLint construct (functions etc.) usage depends on version of Node.js.

Is there no way then to achieve this than to ask all developers to set this themselves in the remote SHH config?

**Comment by rdsedmundo** [comment]
I'm running in macOS, and changing the config via `.vscode/settings.json`. I used `volta` to manage by Node.js version if that matters, and again, this has been working for years and somehow it broke in the last <2 weeks now.

**Comment by dbaeumer** [comment]
@thernstig you can also set it in the workspace settings (e.g..vscode/settings.json). When you run in a remote SSH setup the ESLint extension run on the remote machine, hence the settings of the remote machine apply and not the local user settings. This is how VS Code works.

@rdsedmundo I just tested this locally and using `eslint.runtime` in the workspace settings still works for me. Can you check with some sort of process explorer to see which node process is used to run the `dbaeumer.vscode-eslint-2.4.0/server/out/eslintServer.js` under

**Comment by thernstig** [comment]
@dbaeumer of that I am aware. What I wondered was if setting it in workspace settings did not work, considering you said that for WSL I needed to set it there. But from your text above it seems you confirmed setting it in `.vscode/settings.json` should work also for the setting `"eslint.runtime": "node"`.

But then if it is allowed to set it in the workspace settings when running with remote SSH, I would guess there is a newly introduced bug somewhere. I never seen this before for years, but it started to happen recently probably during the last VS Code or ESLint extension upgrade.

**Comment by rdsedmundo** [comment]
@dbaeumer this is super weird, I haven't really changed anything but from yesterday to today it started working again... I'll let you know if it breaks again and try to check for the process info as you suggested.

**Comment by dbaeumer** [comment]
@thernstig you could enable tracing in the ESLint server using `"eslint.trace.server": "messages"`. When it happens you could provide me with the ESLint output channel which should have some information about which node version got used.

**Comment by thernstig** [comment]
@dbaeumer will do.

To summarize all these lengthy discussions: We set `"eslint.runtime": "node"` in our workspace settings `.vscode/settings.json` and have been for year(s). We recently started to get the faults seen in the original post. Hence I assume it really is a big as it should not occur.

**Comment by koshic** [comment]
@dbaeumer have the same issue recently. May be it related to https://github.com/lukechilds/zsh-nvm (need to investigate a bit), because "eslint.runtime": "MY_HOME/.nvm/versions/node/v19.8.1/bin/node" works fine. 

Stack trace with 'node':
```
[Info  - 01:59:29] ESLint server is starting.
[Info  - 01:59:30] ESLint server stopped.
[Error - 01:59:30] ESLint client: couldn't create connection to server.
Launching server using runtime node failed. Error: spawn node ENOENT
[Error - 01:59:30] Starting the server failed.
Launching server using runtime node failed. Error: spawn node ENOENT
[Error - 01:59:37] Restarting client failed
Error: Client is not running and can't be stopped. It's current state is: startFailed
	at w.shutdown (<my home>/.vscode/extensions/dbaeumer.vscode-eslint-2.4.0/client/out/extension.js:1:103973)
	at w.stop (<my home>/.vscode/extensions/dbaeumer.vscode-eslint-2.4.0/client/out/extension.js:1:103554)
	at w.stop (<my home>/.vscode/extensions/dbaeumer.vscode-eslint-2.4.0/client/out/extension.js:1:265270)
	at w.restart (<my home>/.vscode/extensions/dbaeumer.vscode-eslint-2.4.0/client/out/extension.js:1:265137)
	at <my home>/.vscode/extensions/dbaeumer.vscode-eslint-2.4.0/client/out/extension.js:1:382698
	at c.h (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:96:108784)
	at c.$executeContributedCommand (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:96:109688)
	at a.N (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:106:11223)
	at a.M (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:106:10941)
	at a.H (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:106:10034)
	at a.G (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:106:9015)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:106:7803
	at f.invoke (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:63:145)
	at m.deliver (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:63:2066)
	at d.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:63:1704)
	at p.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:72:14907)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:122:16556
	at f.invoke (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:63:145)
	at m.deliver (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:63:2066)
	at d.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:63:1704)
	at p.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:72:14907)
	at MessagePortMain.<anonymous> (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:122:14682)
	at MessagePortMain.emit (node:events:526:28)
	at MessagePortMain._internalPort.emit (node:electron/js2c/utility_init:5:364)
```

**Comment by dbaeumer** [comment]
The ESLint server is relying on the fact that node is available on the PATH or you provided an absolute path to it. If `zsh-nvm` does some PATH magic it certainly might be the cause of this issue.

**Comment by koshic** [comment]
Sure, I just provided my temporary issue as an illustration, because it was fixed by proper nvm setup.

BTW, may be it's possible to improve error message a bit? "Error: spawn node ENOENT" -> 'Error: spawn node ENOENT, PATH=xxx, cwd=yyy', or something like that. Now it's a black box, and debugging (especially for people not so familiar with OS / shell) is really hard.

**Comment by rdsedmundo** [comment]
@dbaeumer I was able to reproduce this consistently now, for my case it happens when I log out of my computer and check the option [Reopen windows when logging back in](https://support.apple.com/en-us/HT204005), and then log in again. Even if I perform "VSCode: Reload window" several times it still doesn't work, however if I fully kill the process (CMD+Q) and re-open it, then the config works again.

This used to work in the past as I had mentioned above, because I have been using this extension for years. I'd imagine though this is more likely to be either a regression in VSCode itself, or in the newer versions of MacOS that changed something? I have macOS 13.2.1.

**Comment by thernstig** [comment]
This failure is done for me in VS Code in Windows, working remotely against an SSH machine. So it is not macOS specific.

As mentioned before, this has never been a problem before but starting occurring a few releases ago.

**Comment by dbaeumer** [comment]
I tried to reproduce this in a local SSH setup but wasn't able to do so. I actually thing that this is not caused by the ESLint extension itself but may be some change in the remote SSH extension and how it sets up the environment. @thernstig what happens if you use an absolute path to the node executable. Does it happen as well?

**Comment by thernstig** [comment]
@dbaeumer I have not tested, but that is not feasible for me as we use `nvm` and automatically load the version per project. Which we have done for years and not had this problem I see here now. Of course it could be one of the culprits for the reason this happens.

@dbaeumer if you want to keep the issue list clean, I am fine with closing this until I can actually prove exactly what happens. I have added `"eslint.trace.server": "messages"` as you recommended earlier, so if it happens again I might understand it better looking at the logs from ESlint.

**Comment by dbaeumer** [comment]
Thanks for investigating further. 

I will still keep the issue open

**Comment by thernstig** [comment]
@dbaeumer I just got the issue again. I have set `"eslint.trace.server": "messages"` both in the User, Remote SSH and Workspace settings. It seems to give no information about which Node version gets used. Probably because the error indicates it does not even find it.

Restarting VS Code does not help.

```
[Info  - 5:29:08 PM] ESLint server is starting.
[Info  - 5:29:08 PM] ESLint server stopped.
[Error - 5:29:08 PM] ESLint client: couldn't create connection to server.
Launching server using runtime node failed. Error: spawn node ENOENT
[Error - 5:29:08 PM] Starting the server failed.
Launching server using runtime node failed. Error: spawn node ENOENT
```

If I open the terminal I see:
```sh
~/code/cnom (jsdoc)> node -v
v18.14.2
```

Using the command `ESLint: Restart ESLint Server` does not help. 
```
[Info  - 5:30:58 PM] ESLint server is starting.
[Info  - 5:30:58 PM] ESLint server stopped.
[Error - 5:30:58 PM] ESLint client: couldn't create connection to server.
Launching server using runtime node failed. Error: spawn node ENOENT
[Error - 5:30:58 PM] Starting the server failed.
Launching server using runtime node failed. Error: spawn node ENOENT
[Error - 5:32:36 PM] Restarting client failed
Error: Client is not running and can't be stopped. It's current state is: startFailed
	at w.shutdown (/home/userA/.vscode-server/extensions/dbaeumer.vscode-eslint-2.4.0/client/out/extension.js:1:103911)
	at w.stop (/home/userA/.vscode-server/extensions/dbaeumer.vscode-eslint-2.4.0/client/out/extension.js:1:103492)
	at w.stop (/home/userA/.vscode-server/extensions/dbaeumer.vscode-eslint-2.4.0/client/out/extension.js:1:265208)
	at w.restart (/home/userA/.vscode-server/extensions/dbaeumer.vscode-eslint-2.4.0/client/out/extension.js:1:265075)
	at /home/userA/.vscode-server/extensions/dbaeumer.vscode-eslint-2.4.0/client/out/extension.js:1:382636
	at m.h (/home/userA/.vscode-server/bin/e344f1f539a80912a0e9357cec841f36ce97a4e2/out/vs/workbench/api/node/extensionHostProcess.js:99:125797)
	at m.$executeContributedCommand (/home/userA/.vscode-server/bin/e344f1f539a80912a0e9357cec841f36ce97a4e2/out/vs/workbench/api/node/extensionHostProcess.js:99:126701)
	at c.N (/home/userA/.vscode-server/bin/e344f1f539a80912a0e9357cec841f36ce97a4e2/out/vs/workbench/api/node/extensionHostProcess.js:109:11655)
	at c.M (/home/userA/.vscode-server/bin/e344f1f539a80912a0e9357cec841f36ce97a4e2/out/vs/workbench/api/node/extensionHostProcess.js:109:11373)
	at c.H (/home/userA/.vscode-server/bin/e344f1f539a80912a0e9357cec841f36ce97a4e2/out/vs/workbench/api/node/extensionHostProcess.js:109:10454)
	at c.G (/home/userA/.vscode-server/bin/e344f1f539a80912a0e9357cec841f36ce97a4e2/out/vs/workbench/api/node/extensionHostProcess.js:109:9432)
	at /home/userA/.vscode-server/bin/e344f1f539a80912a0e9357cec841f36ce97a4e2/out/vs/workbench/api/node/extensionHostProcess.js:109:8220
	at E.invoke (/home/userA/.vscode-server/bin/e344f1f539a80912a0e9357cec841f36ce97a4e2/out/vs/workbench/api/node/extensionHostProcess.js:63:145)
	at h.deliver (/home/userA/.vscode-server/bin/e344f1f539a80912a0e9357cec841f36ce97a4e2/out/vs/workbench/api/node/extensionHostProcess.js:63:2121)
	at n.fire (/home/userA/.vscode-server/bin/e344f1f539a80912a0e9357cec841f36ce97a4e2/out/vs/workbench/api/node/extensionHostProcess.js:63:1729)
	at p.fire (/home/userA/.vscode-server/bin/e344f1f539a80912a0e9357cec841f36ce97a4e2/out/vs/workbench/api/node/extensionHostProcess.js:72:14916)
	at /home/userA/.vscode-server/bin/e344f1f539a80912a0e9357cec841f36ce97a4e2/out/vs/workbench/api/node/extensionHostProcess.js:125:16654
	at E.invoke (/home/userA/.vscode-server/bin/e344f1f539a80912a0e9357cec841f36ce97a4e2/out/vs/workbench/api/node/extensionHostProcess.js:63:145)
	at h.deliver (/home/userA/.vscode-server/bin/e344f1f539a80912a0e9357cec841f36ce97a4e2/out/vs/workbench/api/node/extensionHostProcess.js:63:2121)
	at n.fire (/home/userA/.vscode-server/bin/e344f1f539a80912a0e9357cec841f36ce97a4e2/out/vs/workbench/api/node/extensionHostProcess.js:63:1729)
	at p.fire (/home/userA/.vscode-server/bin/e344f1f539a80912a0e9357cec841f36ce97a4e2/out/vs/workbench/api/node/extensionHostProcess.js:72:14916)
	at s.E (/home/userA/.vscode-server/bin/e344f1f539a80912a0e9357cec841f36ce97a4e2/out/vs/workbench/api/node/extensionHostProcess.js:72:18982)
	at /home/userA/.vscode-server/bin/e344f1f539a80912a0e9357cec841f36ce97a4e2/out/vs/workbench/api/node/extensionHostProcess.js:72:16970
	at E.invoke (/home/userA/.vscode-server/bin/e344f1f539a80912a0e9357cec841f36ce97a4e2/out/vs/workbench/api/node/extensionHostProcess.js:63:145)
	at h.deliver (/home/userA/.vscode-server/bin/e344f1f539a80912a0e9357cec841f36ce97a4e2/out/vs/workbench/api/node/extensionHostProcess.js:63:2121)
	at n.fire (/home/userA/.vscode-server/bin/e344f1f539a80912a0e9357cec841f36ce97a4e2/out/vs/workbench/api/node/extensionHostProcess.js:63:1729)
	at d.acceptChunk (/home/userA/.vscode-server/bin/e344f1f539a80912a0e9357cec841f36ce97a4e2/out/vs/workbench/api/node/extensionHostProcess.js:72:12647)
	at /home/userA/.vscode-server/bin/e344f1f539a80912a0e9357cec841f36ce97a4e2/out/vs/workbench/api/node/extensionHostProcess.js:72:11934
	at E.invoke (/home/userA/.vscode-server/bin/e344f1f539a80912a0e9357cec841f36ce97a4e2/out/vs/workbench/api/node/extensionHostProcess.js:63:145)
	at h.deliver (/home/userA/.vscode-server/bin/e344f1f539a80912a0e9357cec841f36ce97a4e2/out/vs/workbench/api/node/extensionHostProcess.js:63:2121)
	at n.fire (/home/userA/.vscode-server/bin/e344f1f539a80912a0e9357cec841f36ce97a4e2/out/vs/workbench/api/node/extensionHostProcess.js:63:1729)
	at n.u (/home/userA/.vscode-server/bin/e344f1f539a80912a0e9357cec841f36ce97a4e2/out/vs/workbench/api/node/extensionHostProcess.js:72:28899)
```

**Disabling the ESLint plugin, reloading VS Code, and enabling it again (without reloading) does make it work again.**

**Comment by dbaeumer** [comment]
I looked through the code again and what happens is the following:

- the client tries to spawn the server using `child_process.spawn('node', ....)`
- `node` for some reason isn't on the path hence it can't be found and the client can't start the server.

@roblourens do you have any idea why `node` can't be found sometimes in a remote ssh setup

@thernstig is it important for you to use a custom runtime. If you are happy with node `16.17.1` you can remove the setting and simply use the node version VS Code bundles.

**Comment by thernstig** [comment]
@dbaeumer it is important, as some ESLint features depend on what ECMAScript version is used, which correlates with the Node version.

@dbaeumer an idea why `node` is not on the path at times. It seems me and others use systems to load the `node` version per project/directory. E.g. via `direnv` or other similar means.

Basically what happens is that the `node` binary is on the path once the shell has completed loading. In this case the `fish` shell. See here:

```sh
~/code/projectA (TEST)> which node
/home/userA/.local/share/nvm/v18.14.2/bin/node
~/code/projectA (TEST)> cd ..
direnv: unloading
~/code> which node
~/code [1]> cd projectA/
direnv: loading ~/code/projectA/.envrc
direnv: loading .env.dev
direnv: using nvm
direnv: using node
direnv: Successfully loaded NodeJS v18.14.2 (via .nvmrc), from prefix (/home/userA/.local/share/nvm/v18.14.2)
direnv: export +ANSIBLE_CONFIG +CPATH +DOCKER_BUILDKIT +KUBECONFIG +LD_LIBRARY_PATH +LIBRARY_PATH +MANPATH +PKG_CONFIG_PATH +PLAYWRIGHT_BROWSERS_PATH ~PATH
~/code/projectA (TEST)> which node
/home/userA/.local/share/nvm/v18.14.2/bin/node
~/code/projectA (TEST)>
```

Is it that `child_process.spawn('node', ....)` is spawned before the shell has loaded?

**Comment by roblourens** [comment]
> @roblourens do you have any idea why node can't be found sometimes in a remote ssh setup

Which "node" is this supposed to be? Do we add it to PATH?

**Comment by dbaeumer** [comment]
Actually that would be something @roblourens needs to answer.  The extension host sees the environment of the remote server which I don't know in which shell context it is started.

**Comment by roblourens** [comment]
Sorry I don't fully understand the situation, but in other places I'm aware of when an extension wants to spawn its own node process, I think that we spawn `process.execPath` which is the EH's node. If you spawn `node` then you might get the user's `node` or something else.

**Comment by koshic** [comment]
I think it's need to add some debug code into extension itself and dump PATH / env / 'which node' right before spawn call.

**Comment by dbaeumer** [comment]
@koshic good idea. I will log the PATH when starting the server fails.

**Comment by roblourens** [comment]
Now I understand, thanks. If you grab the log from the Remote-SSH output channel, you can see the environment the the vscode server was started in. That's the environment that the remote server gets and that is inherited by the remote EH.

You called out the fish shell- actually we usually fail to connect at all when fish is the default shell for ssh connections https://github.com/microsoft/vscode-remote-release/issues/2509. But it seems likely that some configuration script you have isn't getting run in this case so node is left out of your PATH.

**Comment by dbaeumer** [comment]
@thernstig can you have a look at the `Remote-SSH output channel` for the environment.

**Comment by roblourens** [comment]
Maybe run the command "Kill VS Code Server on Host" first just to make sure that we are seeing the environment from the session that started the server

**Comment by thernstig** [comment]
@dbaeumer Since I saw @roblourens asking for this, I have kept a mental note. But since it is intermittent, I will have to see next time I get it as I cannot always replicate it.

@roblourens when you say "first" do you mean before checking `Remote-SSH output channel` and adding the output here in the issue?

**Comment by roblourens** [comment]
My comment was to run that command before reproducing the issue. I'm not sure why it would be intermittent- it doesn't seem like PATH is going to change.

You can grab the log when you see the issue, but it may or may not help, because if the current session connected to a remote vscode server that had already been started in a previous session then the log won't show the environment for the earlier session that started the server.

**Comment by dbaeumer** [comment]
@thernstig which version of the ESLint extension are you using. I added logging to 2.4.2 for this case that print the path to the ESLint output channel when this happens. See

https://insiders.vscode.dev/github/microsoft/vscode-eslint/blob/release/2.4.2/client/src/extension.ts#L146

**Comment by thernstig** [comment]
@dbaeumer I am using 2.4.2 right now, but at the time of writing the above post I am not sure. I will continue monitoring and report back.

**Comment by Nettsentrisk** [comment]
I have recently discovered that ESLint was not working in VSCode when combined with using Volta, as I [mentioned here](https://github.com/volta-cli/volta/issues/1119#issuecomment-1736197359).

Is there any known work-around or possible fix in the pipeline for this?

**Comment by dbaeumer** [comment]
I don't know how volta manages internally different node version and package managers. The ESLint extension using standard node features to find global installed packages `require.resolve` plus some package manager specific code to determine the global installation path (see https://insiders.vscode.dev/github/microsoft/vscode-eslint/blob/main/server/src/eslint.ts#L1163). Might be that we need a special code path here for Volta. A PR is welcome since I have no experiences with Volta

**Comment by magnusriga** [comment]
I just updated VC Code and started getting the same error:

> Launching server using runtime /home/username/.nvm/versions/node/v20.1.0/bin/node failed. Error: spawn /home/magnus/.nvm/versions/node/v20.1.0/bin/node ENOENT
> 
> ESLint client: couldn't create connection to server.

`which node` logs: /home/username/.nvm/versions/node/v20.7.0/bin/node
`node -v` logs: v20.7.0

As seen, ESLint tries to use an old version of node. Any idea where it gets that version and why it is not using the node from the PATH?

**Comment by dbaeumer** [comment]
A special node runtime sis only used if the `eslint.runtime` setting is used. Otherwise node that ships with VS Code is used. Could it be that you have set that setting?

**Comment by dbaeumer** [comment]
@magnusriga I would only use a node version different the one the come with VS Code if you need to (e.g. using a eslint plugin that requires some special node features)

**Comment by thernstig** [comment]
@dbaeumer could I ask why your recommendation is to use the one that comes with VS Code? Most other linters and VS Code extensions I am aware of defaults to using the one "from environment".

Examples:
- https://marketplace.visualstudio.com/items?itemName=charliermarsh.ruff
`importStrategy` default is `fromEnvironment`.
- The Python extension by default loads the venv from environment.
- https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode does
- etc. etc.

It makes more sense to me at least. Each project, old or new, comes with a specific Node version. Imagine you work in multiple open source repositories. Most have a `.nvmr` or a `.node-version` file. If I jump around between these, the Node version and thus implicitly the ESLint features changes depending on this.

To me the best solution would be to do like Ruff, where you fall back to the built-in one if you cannot find one from the environment:

<html>
<body>


importStrategy | fromEnvironment | Strategy for loading the ruff executable. fromEnvironment picks up Ruff from the environment, falling back to the bundled version if needed. useBundled uses the version bundled with the extension.
-- | -- | --



</body>
</html>

**Comment by eldarshamukhamedov** [comment]
> I would only use a node version different the one the come with VS Code if you need to (e.g. using a eslint plugin that requires some special node features)

Every org I've ever worked at ran ESLint via CI, build tools, and/or terminal, in addition to devs using it with VS Code, so it is very important to be able to force the VS Code plugin to use the same version of Node as the rest of the application stack. Who knows what version of Node VS Code is going to choose to ship tomorrow; it's meant for use with tools/extensions/internal VS Code features that don't have local app NPM dependencies, and ESLint will almost always have local dependencies.

That said, there is perhaps a biggest VS Code extension issue here: it's not always easy to force VS Code to use the specific version of Node that version managers install. The bootstrapping process for a Node instance that an extension uses is obscure and I've had to wrestle with it many times (e.g. Volta+Prettier/ESLint, Jest test runner, etc.).

**Comment by dbaeumer** [comment]
@eldarshamukhamedov there is a setting to control which node version to use `eslint.runtime`. This can even point to  a script where you can do some magic in case you need to.

**Comment by dbaeumer** [comment]
I will close the issue. For the request of using a default installed Node version see #1727.

**Comment by thernstig** [comment]
@dbaeumer I have not seen this issue in a long time now, but I will surely revert back if it happens again. Thanks for your patience and kind support.

**Comment by dbaeumer** [comment]
Would you be interested in looking into a PR for such a hack?

**Comment by thernstig** [comment]
@dbaeumer possibly, though I personally feel wary about such a solution where an extension (vscode-eslint) depends/checks for one other specific extension (direnv-vscode), as there could be other extensions altering the environment. Maybe it is an intermediate solution and a post should be made on https://github.com/microsoft/vscode/? I am not sure how to phrase such an issue there though, or if it would even get attention.

What I have seen is that restarting the ESLint server does not help either. What would that indicate?

**Comment by dbaeumer** [comment]
> What I have seen is that restarting the ESLint server does not help either. What would that indicate?

The ESLint server inherits the environment from the extension host (e.g. the process running all extensions). If a restart doesn't help that means that the extension host doesn't have an updated environment either. I actually don't know how the direnv extension is altering the envirnment to understand why it is not reflected in the extension host.

**Comment by dbaeumer** [comment]
One idea to find this out is using a dummy extension and run it under the debugger and inspect process.env.

**Comment by thernstig** [comment]
@dbaeumer thanks for the idea, a bit over my knowledge level as I never programmed dummy extensions, but I will let this simmer a bit more. I suppose the idea of posting this as a feature request at the vscode repo, for a new event, is not a good idea then?

**Comment by dbaeumer** [comment]
@thernstig I think we need to first understand what exactly `direnvv-vscode` does to inject the environment.

**Comment by thernstig** [comment]
@dbaeumer with the info from @mkhl above, I can only see two options:
1. VS Code implements a new event, interface etc. to handle extensions wanting to update environments, and that extensions can listen for environment updates.
2. That vscode-eslint does a similar solution as https://github.com/ocamllabs/vscode-ocaml-platform/pull/1322

**Comment by dbaeumer** [comment]
I actually do (2). When I launch the server I has Node API to do so which takes the current env into consideration.

The other workaround I see is to add a setting that makes this extension wait for the activation of the env extension.

**Comment by thernstig** [comment]
Well, then I am stumped. @dbaeumer I do not understand how the extension can take the latest env on commands, since the original problem described even happens when executing the command `ESLint: Restart ESLint Server`, which I then would assume would take the latest env and then it should have worked.

**Comment by thernstig** [comment]
@dbaeumer is that code doing what 2) above shows as in https://github.com/ocamllabs/vscode-ocaml-platform/pull/1322? It says it does it on every command, not every server start. It is possible I misunderstood you of course.

@mkhl are you comfortable enough reading this extensions code to see something? I am unfortunately not wellversed in VS Code extension authoring.

**Comment by dbaeumer** [comment]
@thernstig the eslint server is a separate process with its own environment. What I ensure is that I inject the CURRENT extension host environment into that process when I launch the server. So if direnv has changed the env and the server is re-started it should see that env.

**Comment by thernstig** [comment]
@dbaeumer then it is possible the problem for restarting is another one, as it does not want to do that:

```sh
[Error - 9:33:46 AM] Restarting client failed
Error: Client is not running and can't be stopped. It's current state is: startFailed
	at b.shutdown (/home/userA/.vscode-server/extensions/dbaeumer.vscode-eslint-2.4.4/client/out/extension.js:1:104688)
	at b.stop (/home/userA/.vscode-server/extensions/dbaeumer.vscode-eslint-2.4.4/client/out/extension.js:1:104269)
	at b.stop (/home/userA/.vscode-server/extensions/dbaeumer.vscode-eslint-2.4.4/client/out/extension.js:1:270385)
	at b.restart (/home/userA/.vscode-server/extensions/dbaeumer.vscode-eslint-2.4.4/client/out/extension.js:1:270252)
	at /home/userA/.vscode-server/extensions/dbaeumer.vscode-eslint-2.4.4/client/out/extension.js:1:387592
	at u.h (/home/userA/.vscode-server/cli/servers/Stable-863d2581ecda6849923a2118d93a088b0745d9d6/server/out/vs/workbench/api/node/extensionHostProcess.js:150:184839)
	at u.$executeContributedCommand (/home/userA/.vscode-server/cli/servers/Stable-863d2581ecda6849923a2118d93a088b0745d9d6/server/out/vs/workbench/api/node/extensionHostProcess.js:150:185699)
	at s.S (/home/userA/.vscode-server/cli/servers/Stable-863d2581ecda6849923a2118d93a088b0745d9d6/server/out/vs/workbench/api/node/extensionHostProcess.js:147:5519)
	at s.Q (/home/userA/.vscode-server/cli/servers/Stable-863d2581ecda6849923a2118d93a088b0745d9d6/server/out/vs/workbench/api/node/extensionHostProcess.js:147:5285)
	at s.M (/home/userA/.vscode-server/cli/servers/Stable-863d2581ecda6849923a2118d93a088b0745d9d6/server/out/vs/workbench/api/node/extensionHostProcess.js:147:4375)
	at s.L (/home/userA/.vscode-server/cli/servers/Stable-863d2581ecda6849923a2118d93a088b0745d9d6/server/out/vs/workbench/api/node/extensionHostProcess.js:147:3454)
	at p.value (/home/userA/.vscode-server/cli/servers/Stable-863d2581ecda6849923a2118d93a088b0745d9d6/server/out/vs/workbench/api/node/extensionHostProcess.js:147:2241)
	at n.y (/home/userA/.vscode-server/cli/servers/Stable-863d2581ecda6849923a2118d93a088b0745d9d6/server/out/vs/workbench/api/node/extensionHostProcess.js:80:1902)
	at n.fire (/home/userA/.vscode-server/cli/servers/Stable-863d2581ecda6849923a2118d93a088b0745d9d6/server/out/vs/workbench/api/node/extensionHostProcess.js:80:2119)
	at r.fire (/home/userA/.vscode-server/cli/servers/Stable-863d2581ecda6849923a2118d93a088b0745d9d6/server/out/vs/workbench/api/node/extensionHostProcess.js:105:14091)
	at p.value (/home/userA/.vscode-server/cli/servers/Stable-863d2581ecda6849923a2118d93a088b0745d9d6/server/out/vs/workbench/api/node/extensionHostProcess.js:173:8050)
	at n.y (/home/userA/.vscode-server/cli/servers/Stable-863d2581ecda6849923a2118d93a088b0745d9d6/server/out/vs/workbench/api/node/extensionHostProcess.js:80:1902)
	at n.fire (/home/userA/.vscode-server/cli/servers/Stable-863d2581ecda6849923a2118d93a088b0745d9d6/server/out/vs/workbench/api/node/extensionHostProcess.js:80:2119)
	at r.fire (/home/userA/.vscode-server/cli/servers/Stable-863d2581ecda6849923a2118d93a088b0745d9d6/server/out/vs/workbench/api/node/extensionHostProcess.js:105:14091)
	at u.z (/home/userA/.vscode-server/cli/servers/Stable-863d2581ecda6849923a2118d93a088b0745d9d6/server/out/vs/workbench/api/node/extensionHostProcess.js:105:17156)
	at p.value (/home/userA/.vscode-server/cli/servers/Stable-863d2581ecda6849923a2118d93a088b0745d9d6/server/out/vs/workbench/api/node/extensionHostProcess.js:105:15608)
	at n.y (/home/userA/.vscode-server/cli/servers/Stable-863d2581ecda6849923a2118d93a088b0745d9d6/server/out/vs/workbench/api/node/extensionHostProcess.js:80:1902)
	at n.fire (/home/userA/.vscode-server/cli/servers/Stable-863d2581ecda6849923a2118d93a088b0745d9d6/server/out/vs/workbench/api/node/extensionHostProcess.js:80:2119)
	at p.acceptChunk (/home/userA/.vscode-server/cli/servers/Stable-863d2581ecda6849923a2118d93a088b0745d9d6/server/out/vs/workbench/api/node/extensionHostProcess.js:105:11865)
	at /home/userA/.vscode-server/cli/servers/Stable-863d2581ecda6849923a2118d93a088b0745d9d6/server/out/vs/workbench/api/node/extensionHostProcess.js:105:11152
	at Socket.y (/home/userA/.vscode-server/cli/servers/Stable-863d2581ecda6849923a2118d93a088b0745d9d6/server/out/vs/workbench/api/node/extensionHostProcess.js:170:13198)
	at Socket.emit (node:events:514:28)
	at addChunk (node:internal/streams/readable:324:12)
	at readableAddChunk (node:internal/streams/readable:297:9)
	at Readable.push (node:internal/streams/readable:234:10)
	at Pipe.onStreamRead (node:internal/stream_base_commons:190:23)
```

**Comment by dbaeumer** [comment]
Is there anything more in the Output channel. Looks like a previous restart has failed.

**Comment by thernstig** [comment]
@dbaeumer it is the same output as in the original post. That output starts with:

```sh
[Error - 11:21:40 AM] ESLint client: couldn't create connection to server.
```

**Comment by mkhl** [comment]
@thernstig have you checked the `direnv` Output channel? Does it set the `PATH` you're expecting?

If I understand correctly you're observing the problem in remote SSH workspaces. Does it also occur in local workspaces?

**Comment by dbaeumer** [comment]
> The previous start failed due to node not being found. Then restarting the client does not fail. It should have if it re-reads the env as the extension host env should contain the proper PATH.

This explains why the restart doesn't work. The restart fails because the original start fails since it is using the same client object to not loose any internal client state when restarting the server. 

What we could do is to use a new client in the restart case if a previous start failed.

I opened https://github.com/microsoft/vscode-eslint/issues/1808

**Comment by thernstig** [comment]
@dbaeumer that will most likely at least solve the restart part yay :)

Is there a chance that if a start fails, you do a `setTimeout()` for 1 sec to try to create a new client (thus making sure you get a new fresh environment fron the extension host)? Maybe not a great solution in the end, but just asking.

I am still curious if you think I should open a VS Code issue to ask for an extension API regarding environment changes? You are far better of to judge if that would make sense or not than I am.

**Comment by dbaeumer** [comment]
> I am still curious if you think I should open a VS Code issue to ask for an extension API regarding environment changes? You are far better of to judge if that would make sense or not than I am.

Honestly I think such an API request will not be implemented due to the fact the NodeJS doesn't provide it. It would a require poll/compare implementation which is never good.
