### ISSUE TITLE
Git window: "Error: Path must be a string. Received undefined"

### ISSUE THREAD

**Issue by brianegan** [Microsoft/vscode-eslint#186]
As a user, when I have ESLint installed, and I modify a JS file, and I navigate to the Git window, and I select a JS file, I see the following error:

"Path must be a string. Received undefined"

Screenshot:

![screenshot 2016-12-19 12 03 52](https://cloud.githubusercontent.com/assets/126604/21327309/5f0bf928-c5e3-11e6-8149-221b94337374.png)

**Comment by dbaeumer** [comment]
@brianegan I can't reproduce this. Which version of ESLint are you using. Node changed the path API to throw if args aren't strings and this requires to uses the latest version of the ESLint module.

**Comment by icetbr** [comment]
I can confirm the error in  "eslint": "^1.10.3". Fixed in "eslint": "3.12.2".

**Comment by dbaeumer** [comment]
@brianegan objection to close the issue?

**Comment by jthomas1** [comment]
I am getting this same error with eslint v3.16.0 so maybe they broke it again?

**Comment by jungchris** [comment]
@dbaeumer I disabled ESLint 1.2.6 and issue doesn't appear on VS Code Insiders (v1.10.0-insider)

**Comment by jiqiangbing** [comment]
I am getting this same error and I disabled eslint plugin then error does't appear.
![qq 20170225015342](https://cloud.githubusercontent.com/assets/3283628/23314578/7c339d0e-fafd-11e6-9c5f-d285e480ee83.png)

**Comment by dbaeumer** [comment]
@jiqiangbing, @jungchris which version of the eslint npm package are you using?

**Comment by dbaeumer** [comment]
I tried this again today and I can't reproduce this. Can someone share a GitHub repository that I can clone that reveals the problem?

**Comment by jiqiangbing** [comment]
@dbaeumer v3.16.1. And when I click a js file in the SCM panel could probably cause this problem (see the screenshot above). But I also encounter such problem in the explorer panel when I use eslint plugin in a big project.
the .eslintrc is https://gist.github.com/jiqiangbing/cdfd7f8c51487c66e9998cf7857106f6

**Comment by jthomas1** [comment]
I am on ubuntu 16.04, eslint v3.16.0, node 6.9.2

![image](https://cloud.githubusercontent.com/assets/3570594/23366308/225d8c06-fcfe-11e6-8ce5-ccc9d2403bd3.png)

**Comment by dbaeumer** [comment]
OK. I fixed the problem with the git index file by not validating them. However I would be interested in a reproducible case for seeing this when opeing a file from the explorer. @jiqiangbing could you provide such a case.

**Comment by jiqiangbing** [comment]
I got it, my project's package.json had `  "eslint": "^1.10.3"`. When I upgrade it to 3.16.1, problem sloved which encountered in explorer.

**Comment by dbaeumer** [comment]
@jiqiangbing cool. I will close the issue then.

**Comment by ta-run** [comment]
Still face this issue for 

eslint 3.16.1 
vscode 1.10.2
npm 4.0.5
node 7.4.0

![image](https://cloud.githubusercontent.com/assets/3349253/23982239/2643fc06-0a32-11e7-8664-6c939cfab8d8.png)

**Comment by dbaeumer** [comment]
@ta-run can you share your project so that I can investigate.

**Comment by erlethor** [comment]
I have the same problem every time I open the Git Diff window. Is there a way to exclude git diffs from the validation?

**Comment by pgraci** [comment]
^ i am having the same problem as @erlethor. i get this error every time I open the Diff window.

**Comment by dbaeumer** [comment]
@erlethor @pgraci published 1.2.8 today which should disable all validation of git diff windows.

**Comment by ta-run** [comment]
@dbaeumer can't share the project as it's a corporate one. 
But error's gone after today's update. Thanks :)

**Comment by erlethor** [comment]
Thanks for the quick fix! It worked well.
